baseURL = 'https://blog.geekycat.in/'
languageCode = 'en-us'
title = 'Geekycat Blog'
theme = "hugo-blog-awesome"



[[params.socialIcons]]
name = "github"
url = "https://github.com/geeky-cat"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/kl_sree"

[params]
    goToTop = true
    defaultColor = "dark"
    mainSections = ['posts']
    tocOpen = false

[params.author]
    avatar = "avatar.jpg"
    intro = "Geekycat Blog"
    name = "Sreeram KL"
    description = "Thoughts, stories and ideas."

# set markup.highlight.noClasses=false to enable code highlight
  
[markup]
    [markup.highlight]
        noClasses = false
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
	    startLevel = 2 # ToC starts from H2
	    endLevel = 4 # ToC ends at H4
	    ordered = false # generates <ul> instead of <ol>

[[menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10

[[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20

